#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25
#  in conjunction with Tcl version 8.6
#    Aug 29, 2019 08:17:59 AM IST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global progress_bar
    progress_bar = tk.IntVar()
    global selectedButton
    selectedButton = tk.StringVar()

def AxialScroll(*args):
    print('DeepBrainSeg_support.AxialScroll')
    sys.stdout.flush()

def CorronalScroll(*args):
    print('DeepBrainSeg_support.CorronalScroll')
    sys.stdout.flush()

def FlairView():
    print('DeepBrainSeg_support.FlairView', selectedButton)
    sys.stdout.flush()

def Get_Segmentation():
    print('DeepBrainSeg_support.Get_Segmentation')
    sys.stdout.flush()

def Load_Flair():
    print('DeepBrainSeg_support.Load_Flair')
    sys.stdout.flush()

def Load_T1():
    print('DeepBrainSeg_support.Load_T1')
    sys.stdout.flush()

def Load_T1ce():
    print('DeepBrainSeg_support.Load_T1ce')
    sys.stdout.flush()

def Load_T2():
    print('DeepBrainSeg_support.Load_T2')
    sys.stdout.flush()

def SagitalScroll(*args):
    print('DeepBrainSeg_support.SagitalScroll', int(args[0]))
    sys.stdout.flush()

def SegmentationOverlay():
    print('DeepBrainSeg_support.SegmentationOverlay')
    sys.stdout.flush()

def T1View():
    print('DeepBrainSeg_support.T1View', selectedButton)
    sys.stdout.flush()

def T1ceView():
    print('DeepBrainSeg_support.T1ceView', selectedButton)
    sys.stdout.flush()

def T2View():
    print('DeepBrainSeg_support.T2View', selectedButton)
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import DeepBrainSeg
    DeepBrainSeg.vp_start_gui()




